'use strict';
(()=>{
const $=id=>document.getElementById(id),cfg=MP.config,engine=new MP.Engine(),settings=MP.storage.load(),audio=new MP.Audio(settings),images={},nodes=new Map();
const pointer={x:640,y:350},camera={cx:640,cy:350,z:1,tx:0,ty:0};let view='title',last=performance.now(),toastLeft=0,loaded=false,pendingFinish=false;
const imagePath=(kind,id)=>'./assets/images/'+kind+'/'+id+'.png';
const imageFiles=['backgrounds/moonlit-forest','foregrouds/fog','foregrouds/branches','effects/vanish-particles','camera/camera-hand','camera/camera-aim','ui/album-frame',...cfg.monsters.map(m=>'monsters/'+m.id)];
Promise.all(imageFiles.map(id=>new Promise(resolve=>{const img=new Image();images[id]=img;img.onload=resolve;img.onerror=()=>{console.warn('이미지를 불러오지 못했습니다:',id);resolve();};img.src='./assets/images/'+id+'.png';}))).then(()=>{loaded=true;const b=$('start-button');if(b){b.disabled=false;b.textContent='숲으로 들어가기 →';}const l=$('loading');if(l)l.remove();});
function resize(){$('stage').style.transform='scale('+($('shell').clientWidth/1280)+')';}new ResizeObserver(resize).observe($('shell'));resize();
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastLeft=2;}
function show(html,panel=true){$('screen').innerHTML=html;$('screen').className=panel?'panel-screen':'';$('screen').scrollTop=0;$('stage').classList.remove('playing');$('hud').hidden=true;$('reticle').style.display='none';$('camera').style.display='none';$('world').style.transform='none';audio.music(false);}
function title(){view='title';engine.state='READY';nodes.clear();$('monsters').replaceChildren();show(`<img class="hero-monster" src="${imagePath('monsters','mossantler')}" alt="이끼뿔"><div class="eyebrow">달빛 아래, 미지의 기록</div><h1>괴물 사진사<span>미지의 숲</span></h1><p class="intro-copy">숲이 잠든 시간, 숨겨진 눈빛이 깨어납니다.<br>셔터가 닫히기 전, 그들의 비밀을 담아보세요.</p><div class="actions title-actions"><button class="primary" id="start-button" data-action="new" ${loaded?'':'disabled'}>${loaded?'숲으로 들어가기 →':'숲을 준비하는 중…'}</button><button data-action="help">조작 방법</button></div><div class="actions"><button data-action="collection">괴물 도감 &nbsp; ${settings.discovered.length} / 5</button></div><div class="record">최고 기록 <b>${settings.bestCoins} COINS</b> 최고 등급 <b>${settings.bestGrade}</b></div>${loaded?'':'<p class="loading" id="loading">이미지 리소스를 불러오고 있습니다.</p>'}<div class="hero-caption">SPECIMEN NO. 001<b>이끼뿔 · MOSSANTLER</b>달빛 숲의 오래된 수호자</div>`,false);}
function help(start=false){openModal(`<div class="eyebrow">PHOTOGRAPHER'S GUIDE</div><h2>두 눈이 보이는 순간을 기다리세요.</h2><ol><li>마우스를 움직여 프레임으로 숲을 살펴보세요.</li><li>괴물의 <b>두 눈</b>이 프레임 안에 보이면 왼쪽 클릭으로 촬영합니다.</li><li>작은 중앙 영역에 두 눈을 맞추면 <b>완벽한 사진 · 보상 ×1.5</b>!</li><li>우클릭을 유지해 조준하고, 휠로 1.0 / 1.25 / 1.6 / 2.0배 확대하세요. <b>우클릭을 누른 채 왼쪽 클릭</b>하면 확대 상태에서 촬영합니다.</li><li>필름 5장을 사용하면 <b>R</b>로 재장전합니다. <b>ESC</b>는 일시정지.</li></ol><p>라운드마다 60초 안에 10마리를 촬영하세요. 실패 사진은 3장까지 허용되며 4번째 실패 사진에서 라운드가 종료됩니다. 총 5라운드이며, 획득한 코인으로 장비를 강화할 수 있습니다.</p><p>마우스가 있는 PC 사용을 권장합니다.</p>${start?'<button class="primary" data-action="intro">첫 탐사 준비 →</button>':''}`);}
function intro(){closeModal();view='intro';const r=cfg.rounds[engine.round];show(`<div class="eyebrow">EXPEDITION ${String(engine.round+1).padStart(2,'0')} / 05</div><h2>${['첫 번째 눈빛','속삭이는 나뭇잎','그림자의 발자국','안개 너머의 존재','숲의 마지막 비밀'][engine.round]}</h2><p>${r.time}초 안에 10마리의 두 눈을 기록하세요. 최대 ${r.max}마리가 함께 등장합니다. 실패 사진은 3장까지 허용됩니다.</p><div class="grid collection">${cfg.monsters.slice(0,r.types).map(m=>`<div><img src="${imagePath('monsters',m.id)}" alt="${m.name}"><h3>${m.name}</h3><p>${m.tip}</p></div>`).join('')}</div><div class="actions"><button class="primary" data-action="start">탐사 시작 →</button><button data-action="help">조작 다시 보기</button></div>`);}
function startRound(){if(window.innerWidth<768){openModal('<h2>더 넓은 화면에서 만나요.</h2><p>가로 화면으로 돌리거나 마우스가 있는 PC에서 실행해 주세요. 이 게임은 768px 이상 화면에서 시작할 수 있습니다.</p>');return;}closeModal();engine.startRound();nodes.clear();$('monsters').replaceChildren();pendingFinish=false;view='game';pointer.x=640;pointer.y=350;camera.cx=640;camera.cy=350;camera.z=1;camera.tx=0;camera.ty=0;$('screen').innerHTML='';$('screen').className='empty';$('hud').hidden=false;$('reticle').style.display='block';$('camera').style.display='block';$('stage').classList.add('playing');audio.music(true);last=performance.now();toast('두 눈이 드러나는 순간을 촬영하세요');render();}
function syncCamera(dt){const a=1-Math.exp(-dt/0.09);camera.cx+=( (engine.aiming?640:pointer.x)-camera.cx)*a;camera.cy+=( (engine.aiming?350:pointer.y)-camera.cy)*a;camera.z+=(engine.zoom-camera.z)*(1-Math.exp(-dt/.07));if(Math.abs(camera.z-engine.zoom)<.002)camera.z=engine.zoom;camera.tx=-(camera.z-1)*pointer.x;camera.ty=-(camera.z-1)*pointer.y;}
function drawWorld(){for(const m of engine.targets){let n=nodes.get(m.id);if(['hidden','done','teleport'].includes(m.phase)){if(n)n.style.display='none';continue;}if(!n){n=document.createElement('div');n.className='monster';n.dataset.monsterId=m.id;const img=document.createElement('img');img.src=imagePath('monsters',m.type.id);img.alt=m.type.name;const cover=document.createElement('i');cover.className='eye-cover';const eye=m.type.eyes[1];cover.style.cssText=`left:${eye[0]*100-6}%;top:${eye[1]*100-3}%;width:12%;height:6%;`;img.onerror=()=>{img.style.display="none";n.style.background="radial-gradient(ellipse,#304c40,#112722 70%,transparent 72%)";for(const [ex,ey] of m.type.eyes){const dot=document.createElement("i");dot.style.cssText="position:absolute;left:"+(ex*100)+"%;top:"+(ey*100)+"%;width:8px;height:5px;background:#e5efa4;border-radius:50%;";n.insertBefore(dot,cover);}};n.append(img,cover);$('monsters').append(n);nodes.set(m.id,n);}n.style.display='block';n.style.width=m.w+'px';n.style.height=m.h+'px';n.style.transform=`translate(${m.x}px,${m.y}px)`;n.style.opacity=m.phase==='vanish'?Math.max(0,1-m.age/.8):m.type.id==='mist-wraith'?(engine.levels.night?.9:.57):1;n.style.filter=`brightness(${engine.levels.night?1.4:1})`;n.querySelector('.eye-cover').style.display=m.phase==='oneEye'?'block':'none';n.classList.toggle('captured',m.captured);if(m.captured&&!n.querySelector('.particles')){const p=new Image();p.src=imagePath('effects','vanish-particles');p.className='particles';p.alt='';n.append(p);}}
$('world').style.transform=`translate(${camera.tx}px,${camera.ty}px) scale(${camera.z})`;
}
function render(){drawWorld();$('reticle').style.left=camera.cx-120+'px';$('reticle').style.top=camera.cy-90+'px';$('perfect-zone').style.width=cfg.frame.pw*(1+.1*engine.levels.lens)+'px';$('perfect-zone').style.height=cfg.frame.ph*(1+.1*engine.levels.lens)+'px';const ready=engine.judge(camera);$('reticle').classList.toggle('ready',!!ready.m);$('focus-status').textContent=ready.m?(ready.perfect?'PERFECT / 완벽한 구도':'IN FOCUS / 촬영 가능'):'SEARCHING / 눈빛 탐색';$('camera').src=imagePath('camera',engine.aiming?'camera-aim':'camera-hand');$('camera').style.left=Math.max(0,Math.min(910,camera.cx-185))+'px';$('camera').style.top=(engine.reloadLeft?680:Math.max(470,Math.min(620,camera.cy+160)))+'px';$('round-label').textContent=`ROUND ${String(engine.round+1).padStart(2,'0')} / 05`;$('time').innerHTML=Math.ceil(engine.time)+'<span>s</span>';$('time').classList.toggle('warning',engine.time<=10);$('count').innerHTML=engine.captured+' <em>/ 10</em>';$('progress').style.setProperty('--progress',engine.captured*10+'%');$('coins').textContent=engine.coins;$('failed-count').textContent='실패 사진 '+engine.failed+' / '+cfg.maxFailedPhotos;$('failed-count').classList.toggle('danger',engine.failed>=cfg.maxFailedPhotos);$('film').textContent=engine.film+' / '+engine.capacity;$('zoom').textContent='×'+engine.zoom.toFixed(2).replace(/0$/,'');$('reload-progress').value=engine.reloadLeft?1-engine.reloadLeft/engine.reloadDuration:0;$('reload-ui').querySelector('button').textContent=engine.reloadLeft?'재장전 중…':'R   재장전';}
function snapshot(){const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;const c=canvas.getContext('2d');c.fillStyle='#092023';c.fillRect(0,0,320,240);c.scale(320/240,240/180);c.translate(120-camera.cx,90-camera.cy);c.translate(camera.tx,camera.ty);c.scale(camera.z,camera.z);const draw=(id,x,y,w,h,alpha=1)=>{const im=images[id];if(im?.complete&&im.naturalWidth){c.globalAlpha=alpha;c.drawImage(im,x,y,w,h);c.globalAlpha=1;}};
// Match the background's CSS object-fit: cover, including any crop.
const bg=images['backgrounds/moonlit-forest'];if(bg?.naturalWidth){const scale=Math.max(1280/bg.naturalWidth,720/bg.naturalHeight);draw('backgrounds/moonlit-forest',(1280-bg.naturalWidth*scale)/2,(720-bg.naturalHeight*scale)/2,bg.naturalWidth*scale,bg.naturalHeight*scale);}draw('foregrouds/fog',0,0,1280,720,.13);
for(const m of engine.targets){if(['hidden','done','teleport'].includes(m.phase))continue;c.filter=engine.levels.night?'brightness(1.4)':'none';draw('monsters/'+m.type.id,m.x,m.y,m.w,m.h,m.type.id==='mist-wraith'?(engine.levels.night?.9:.57):1);c.filter='none';if(m.phase==='oneEye'){const e=m.type.eyes[1];c.fillStyle='#101e1b';c.beginPath();c.ellipse(m.x+e[0]*m.w,m.y+e[1]*m.h,m.w*.07,m.h*.035,0,0,Math.PI*2);c.fill();}}
c.save();c.beginPath();c.rect(0,0,1280,108);c.rect(0,597.6,1280,122.4);c.rect(0,108,64,489.6);c.rect(1216,108,64,489.6);c.clip();draw('foregrouds/branches',0,0,1280,720,.62);c.restore();return canvas;}
function shoot(){if(engine.state!=='PLAYING'||engine.paused||engine.reloadLeft||engine.lock)return;let canvas;if(engine.film>0)canvas=snapshot();const photo=engine.shoot(camera);if(photo){photo.canvas=canvas;try{photo.url=canvas.toDataURL('image/jpeg',.78);photo.canvas=null;}catch{photo.url=null;}if(!engine.best||photo.coins>engine.best.coins)engine.best=photo;audio.play('shutter');if(settings.flash){$('flash').classList.remove('fire');void $('flash').offsetWidth;$('flash').classList.add('fire');}}handleEvents();if(engine.state==='PLAYING')render();}
function persist(){settings.discovered=[...new Set([...settings.discovered,...engine.discovered])];MP.storage.save(settings);}
function handleEvents(){for(const event of engine.takeEvents()){switch(event.type){case 'appear':audio.play('monster-appear');break;case 'hide':audio.play('monster-vanish');break;case 'reload':audio.play('reload');break;case 'reloaded':toast('필름 장전 완료');break;case 'warning':audio.play('time-warning');break;case 'message':toast(event.text);break;case 'capture':audio.play(event.photo.quality==='perfect'?'perfect-capture':'capture-success');toast(`${event.photo.quality==='perfect'?'완벽한 사진!':'촬영 성공!'} ${event.photo.name} +${event.photo.coins} 코인`);persist();break;case 'miss':audio.play('capture-fail');toast(event.photo.reason);break;case 'finish':audio.play(event.success?'round-clear':'round-fail');pendingFinish=true;break;}}if(pendingFinish){pendingFinish=false;album();}}
function photoMarkup(p,i,best){return `<button class="photo ${p.quality}" data-photo="${i}"><div class="photo-image">${p.url?`<img src="${p.url}" alt="${p.name} 촬영 사진">`:'<div class="canvas-slot"></div>'}<img class="album-frame" src="${imagePath('ui','album-frame')}" alt=""></div><h3>${p.name} ${p===best?'<span class="badge">BEST</span>':''}</h3><p>${quality(p)} · +${p.coins} 코인</p></button>`;}
function quality(p){return {perfect:'완벽한 사진',success:'촬영 성공',failed:'실패 사진'}[p.quality];}
function stats(){return `<div class="stats"><div><strong>${engine.captured} / 10</strong><span>촬영 성공</span></div><div><strong>${engine.perfect}</strong><span>완벽한 사진</span></div><div><strong>${engine.failed}</strong><span>실패 사진</span></div><div><strong>+${engine.roundEarned}</strong><span>이번 탐사 코인</span></div></div>`;}
function album(){view='album';const best=engine.photos.reduce((a,b)=>!a||b.coins>a.coins?b:a,null);show(`<div class="panel-head"><div><div class="eyebrow">FIELD JOURNAL / ROUND ${engine.round+1}</div><h2>${engine.success?'숲의 비밀을 기록했습니다.':engine.failureReason||'아직 남아 있는 눈빛이 있습니다.'}</h2></div><button class="primary" data-action="${engine.success?(engine.round===4?'final':'shop'):'retry'}">${engine.success?(engine.round===4?'최종 기록 보기 →':'장비 상점 →'):'같은 라운드 재도전 →'}</button></div>${stats()}<p>${engine.bonuses.map(b=>`${b.name} +${b.coins}`).join(' · ')||'획득한 코인과 장비는 재도전해도 유지됩니다.'} &nbsp; / &nbsp; 평가 점수 ${Math.max(0,engine.roundEarned-engine.failed*50)}</p><div class="grid" id="photo-grid">${engine.photos.map((p,i)=>photoMarkup(p,i,best)).join('')}</div>${engine.photos.length?'':'<div class="empty-album">아직 촬영한 사진이 없습니다. 다음 탐사에서 첫 기록을 남겨보세요.</div>'}`);document.querySelectorAll('[data-photo]').forEach(el=>{const p=engine.photos[Number(el.dataset.photo)];if(!p.url&&p.canvas){const copy=document.createElement('canvas');copy.width=320;copy.height=240;copy.style.width='100%';copy.getContext('2d').drawImage(p.canvas,0,0);el.querySelector('.canvas-slot').append(copy);}});}
function shop(){view='shop';show(`<div class="panel-head"><div><div class="eyebrow">THE FIELD STATION</div><h2>다음 탐사를 위한 준비</h2><p>장비는 이번 게임 동안 유지됩니다.</p><div class="shop-wallet" role="status" aria-live="polite"><img src="${imagePath('ui','coin')}" alt=""><span>현재 보유 코인<strong id="shop-coins">${engine.coins.toLocaleString()} <small>코인</small></strong></span></div></div><button class="primary" data-action="next">다음 라운드 →</button></div><div class="grid" style="margin-top:35px">${cfg.equipment.map((item,i)=>{const lv=engine.levels[item.key],price=item.prices[lv];return `<article class="equipment"><img src="${imagePath('ui/equipment',item.id)}" alt=""><span class="badge">LEVEL ${lv} / ${item.prices.length}</span><h3>${item.name}</h3><p>${item.tip}<br>${item.key==='film'?`현재 ${engine.capacity}장`:item.key==='reload'?`현재 ${engine.reloadDuration.toFixed(1)}초`:item.key==='lens'?`현재 +${lv*10}%`:lv?'필터 장착됨':'어두운 숲에서 더 또렷하게'}</p><button data-buy="${i}" ${price===undefined||engine.coins<price?'disabled':''}>${price===undefined?'최대 단계':engine.coins<price?`${price} 코인 · 코인 부족`:`${price} 코인 · 구매`}</button></article>`;}).join('')}</div><div class="actions"><button data-action="album">촬영 앨범 보기</button></div>`);}
function collectionHtml(){return `<div class="grid collection">${cfg.monsters.map(m=>{const known=settings.discovered.includes(m.id);return `<div class="${known?'':'locked'}"><img src="${imagePath('monsters',m.id)}" alt="${known?m.name:'미발견 괴물'}"><h3>${known?m.name:'???'}</h3><p>${known?m.rarity+' · '+m.coins+' 코인':'아직 발견하지 못했습니다'}</p>${known?`<p>${m.tip}</p>`:''}</div>`;}).join('')}</div>`;}
function finalResult(completed=true){closeModal();engine.state='GAME_OVER';engine.paused=false;view='final';persist();if(completed){settings.bestCoins=Math.max(settings.bestCoins,engine.earned);const grades=['S','A','B','C','—'];if(grades.indexOf(engine.grade)<grades.indexOf(settings.bestGrade))settings.bestGrade=engine.grade;MP.storage.save(settings);}show(`<div class="eyebrow">${completed?'EXPEDITION COMPLETE':'EXPEDITION ENDED'}</div><h2>${completed?'당신의 시선이 숲을 기억합니다.':'이번 탐사를 마쳤습니다.'}</h2><div class="stats"><div><strong>${completed?engine.grade:'—'}</strong><span>최종 등급 · 완벽 사진 비율 기준</span></div><div><strong>${engine.earned}</strong><span>총 획득 코인</span></div><div><strong>${engine.totalShots?Math.round(engine.totalSuccess/engine.totalShots*100):0}%</strong><span>촬영 성공률</span></div><div><strong>${engine.totalPerfect}</strong><span>완벽한 사진</span></div></div>${engine.best?.coins?`<p>최고 사진 · ${engine.best.name} · ${quality(engine.best)} · +${engine.best.coins} 코인</p>${engine.best.url?`<img src="${engine.best.url}" style="width:240px" alt="최고 사진">`:''}`:''}<h3>괴물 도감 · ${settings.discovered.length} / 5</h3>${collectionHtml()}<div class="actions"><button class="primary" data-action="new">처음부터 다시 하기</button><button data-action="title">시작 화면으로</button></div>`);}
function pause(){if(engine.state!=='PLAYING')return;if(engine.paused){resume();return;}engine.paused=true;engine.aiming=false;view='paused';audio.music(false);$('stage').classList.remove('playing');$('screen').className='panel-screen';$('screen').innerHTML='<div class="pause-card"><div class="eyebrow">TAKE A BREATH</div><h2>숲도 잠시 기다립니다.</h2><p>타이머와 괴물의 움직임이 멈췄습니다.</p><div class="actions"><button class="primary" data-action="resume">탐사 계속하기</button><button data-action="quit">탐사 종료</button></div></div>';}
function resume(){if(engine.state!=='PLAYING')return;engine.paused=false;view='game';$('screen').className='empty';$('screen').innerHTML='';$('stage').classList.add('playing');last=performance.now();audio.music(true);}
function openModal(html){$('modal-body').innerHTML=html;$('modal').showModal();}function closeModal(){$('modal').close();}
function toggles(){for(const key of ['music','sound','flash'])$(key+'-toggle').textContent=({music:'음악',sound:'효과음',flash:'섬광'}[key])+' '+(settings[key]?'ON':'OFF');}
document.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.buy!==undefined&&view==='shop'){if(engine.buy(Number(btn.dataset.buy))){audio.play('coin');shop();}return;}if(btn.dataset.photo!==undefined&&view==='album'){const p=engine.photos[Number(btn.dataset.photo)];openModal(`<h2>${p.name}</h2>${p.url?`<img class="detail-photo" src="${p.url}" alt="촬영 사진">`:'<div id="detail-canvas"></div>'}<p>${quality(p)} · 줌 ×${p.zoom.toFixed(2)} · +${p.coins} 코인</p><p>${p.reason||'양쪽 눈을 선명하게 담았습니다.'}</p>`);if(!p.url&&p.canvas){const c=p.canvas.cloneNode();c.getContext('2d').drawImage(p.canvas,0,0);$('detail-canvas').append(c);}return;}const a=btn.dataset.action;if(['music','sound','flash'].includes(a)){settings[a]=!settings[a];MP.storage.save(settings);toggles();audio.music(view==='game'&&!engine.paused);return;}switch(a){case 'new':if(loaded){engine.newGame();help(true);}break;case 'help':help();break;case 'intro':intro();break;case 'start':if(view==='intro')startRound();break;case 'collection':openModal('<h2>괴물 도감</h2>'+collectionHtml());break;case 'pause':pause();break;case 'resume':resume();break;case 'quit':finalResult(false);break;case 'reload':engine.reload();handleEvents();break;case 'retry':if(view==='album'&&!engine.success)intro();break;case 'shop':if(view==='album'&&engine.success)shop();break;case 'next':if(view==='shop'){engine.round++;intro();}break;case 'album':album();break;case 'final':if(view==='album'&&engine.success&&engine.round===4)finalResult();break;case 'title':title();break;}});
$('close-modal').addEventListener('click',()=>{const wasNew=$('modal-body').querySelector('[data-action="intro"]');closeModal();if(wasNew)intro();});$('modal').addEventListener('cancel',()=>{if($('modal-body').querySelector('[data-action="intro"]'))queueMicrotask(intro);});
$('stage').addEventListener('pointermove',e=>{if(view!=='game')return;const r=$('stage').getBoundingClientRect();pointer.x=Math.max(120,Math.min(1160,(e.clientX-r.left)*1280/r.width));pointer.y=Math.max(150,Math.min(550,(e.clientY-r.top)*720/r.height));});
MP.bindMouseButtons($('stage'), window, {
  isPlaying: () => view === 'game',
  isReloading: () => engine.reloadLeft > 0,
  setAiming: value => { engine.aiming = value; },
  shoot
});
$('stage').addEventListener('contextmenu',e=>e.preventDefault());$('stage').addEventListener('wheel',e=>{if(view!=='game')return;e.preventDefault();engine.zoomIndex=Math.max(0,Math.min(3,engine.zoomIndex+(e.deltaY<0?1:-1)));toast('줌 ×'+cfg.zoom[engine.zoomIndex]+' · 우클릭을 유지해 확대');},{passive:false});
document.addEventListener('keydown',e=>{if($('modal').open)return;if(e.code==='Escape'&&engine.state==='PLAYING'){e.preventDefault();pause();}if(e.code==='KeyR'&&view==='game'&&!e.repeat){engine.reload();handleEvents();}});window.addEventListener('blur',()=>{engine.aiming=false;if(view==='game')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&view==='game')pause();});
function loop(now){const dt=Math.max(0,(now-last)/1000);last=now;if(view==='game'){engine.update(dt);syncCamera(Math.min(dt,.1));render();handleEvents();}if(toastLeft>0){toastLeft-=dt;if(toastLeft<=0)$('toast').classList.remove('visible');}requestAnimationFrame(loop);}toggles();title();requestAnimationFrame(loop);
})();


