const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');
const context={window:{},console,Set,Math};context.window=context;vm.createContext(context);for(const file of ['config.js','engine.js','storage.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../js',file),'utf8'),context);const {MP}=context;
let tests=0;function test(name,fn){fn();tests++;console.log('PASS '+name);}
const camera={cx:640,cy:350,z:1,tx:0,ty:0};
function align(e,m,z=1){const eyes=m.type.eyes;m.x=(640/z)-(eyes[0][0]+eyes[1][0])/2*m.w;m.y=(350/z)-(eyes[0][1]+eyes[1][1])/2*m.h;return {...camera,z};}
test('five complete rounds, ten unique captures, bonuses and final counters',()=>{const e=new MP.Engine(()=>.25);for(let r=0;r<5;r++){e.round=r;e.startRound();assert.equal(e.targets.length,10);if(r===4)assert.ok(e.targets.some(m=>m.type.id==='mist-wraith'));for(const m of e.targets){m.phase='bothEyes';e.film=e.capacity;e.lock=0;const c=align(e,m,m.type.id==='mist-wraith'?2:1);const p=e.shoot(c);assert.notEqual(p.quality,'failed');assert.equal(m.captured,true);m.phase='done';}assert.equal(e.state,'READY');assert.equal(e.captured,10);assert.equal(e.success,true);assert.equal(e.bonuses.reduce((s,b)=>s+b.coins,0),230);}assert.equal(e.totalSuccess,50);assert.equal(e.totalShots,50);assert.equal(e.grade,'S');});
test('hidden eye cannot succeed, peripheral eyes succeed without perfect reward',()=>{const e=new MP.Engine(()=>.2);e.startRound();const m=e.targets[0];m.phase='oneEye';const c=align(e,m);assert.equal(e.shoot(c).quality,'failed');m.phase='bothEyes';e.lock=0;m.x+=75;assert.equal(e.shoot(c).quality,'success');});
test('one eye outside frame fails; empty and duplicate photos fail',()=>{const e=new MP.Engine(()=>.2);e.startRound();const m=e.targets[0];m.phase='bothEyes';const c=align(e,m);m.x+=120;assert.equal(e.shoot(c).quality,'failed');e.lock=0;align(e,m);assert.equal(e.shoot(c).quality,'perfect');e.lock=0;assert.equal(e.shoot(c).quality,'failed');m.phase='done';e.lock=0;assert.equal(e.shoot(c).quality,'failed');});
test('only nearest valid monster captured per shutter; lock prevents duplicate inputs',()=>{const e=new MP.Engine(()=>.2);e.startRound();for(const m of e.targets.slice(0,2)){m.phase='bothEyes';align(e,m);}e.shoot(camera);assert.equal(e.captured,1);assert.equal(e.film,4);assert.equal(e.shoot(camera),null);assert.equal(e.film,4);});
test('film, reloading, pause, timeout and retry preserve resources',()=>{const e=new MP.Engine(()=>.2);e.startRound();e.film=0;assert.equal(e.shoot(camera),null);assert.equal(e.reload(),true);assert.equal(e.reload(),false);assert.equal(e.shoot(camera),null);e.paused=true;const before=e.time;e.update(20);assert.equal(e.time,before);assert.equal(e.reloadLeft,2);e.paused=false;e.update(2);assert.equal(e.film,5);e.coins=99;e.levels.film=1;e.time=.1;e.update(.2);assert.equal(e.success,false);assert.equal(e.state,'READY');e.startRound();assert.equal(e.coins,99);assert.equal(e.capacity,6);assert.equal(e.film,6);assert.equal(e.targets.filter(m=>m.captured).length,0);});
test('shop prices, bounds and actual equipment effects',()=>{const e=new MP.Engine();assert.equal(e.buy(0),false);e.coins=10000;for(let i=0;i<4;i++){for(let j=0;j<MP.config.equipment[i].prices.length;j++)assert.equal(e.buy(i),true);assert.equal(e.buy(i),false);}assert.equal(e.capacity,8);assert.equal(e.reloadDuration,1.1);assert.equal(e.levels.lens,3);assert.equal(e.levels.night,1);e.startRound();assert.equal(e.buy(0),false);});
test('ghost needs zoom; transformed eye geometry uses world coordinates',()=>{const e=new MP.Engine();e.round=4;e.startRound();const m=e.targets[0];m.type=MP.config.monsters[4];m.w=136;m.h=136;m.phase='bothEyes';align(e,m);assert.equal(e.judge(camera).m,undefined);const c=align(e,m,2);assert.equal(e.judge(c).m,m);c.tx=-300;c.ty=-100;c.cx-=300;c.cy-=100;assert.equal(e.judge(c).m,m);});
test('spawn concurrency, reappearance delay and missed opportunity assistance',()=>{for(let r=0;r<5;r++){const e=new MP.Engine(()=>.25);e.round=r;e.startRound();for(let t=0;t<70;t++){e.update(.1);assert.ok(e.targets.filter(m=>!['hidden','done'].includes(m.phase)).length<=MP.config.rounds[r].max);}}const e=new MP.Engine(()=>.5);e.startRound();e.update(.1);const m=e.targets[0];e.update(5);assert.equal(m.phase,'hidden');assert.ok(m.due-e.clock>=3&&m.due-e.clock<=6);m.misses=2;e.spawn(m);assert.equal(m.duration,m.type.expose*1.2);});
test('weighted pool respects unlocks and ghost guarantees across random runs',()=>{for(let r=0;r<5;r++)for(let run=0;run<100;run++){const e=new MP.Engine();e.round=r;e.startRound();assert.ok(e.targets.every(m=>MP.config.monsters.indexOf(m.type)<MP.config.rounds[r].types));const n=e.targets.filter(m=>m.type.id==='mist-wraith').length;assert.ok(n<=2);if(r===4)assert.ok(n>=1);}});
test('corrupt storage and unavailable localStorage recover safely',()=>{context.localStorage={getItem:()=>'{bad',setItem:()=>{throw Error('quota');}};assert.equal(MP.storage.load().bestCoins,0);context.localStorage.getItem=()=>JSON.stringify({version:1,bestCoins:-1,bestGrade:'ZZ',discovered:['bogus','mossantler'],music:'bad'});const d=MP.storage.load();assert.equal(d.bestCoins,0);assert.equal(d.bestGrade,'—');assert.equal(d.discovered.length,1);assert.equal(d.music,true);});
console.log(`${tests} tests passed`);
